namespace Game.Players;

public enum CharacterStatType
{
	None,
	Health,
	MaxHealth,
	MoveSpeed,
	RunSpeed,
	Stamina,
	MaxStamina,
	Defense,
	CriticalChance,
	PickupRangeRadius,
	HealthRegenPerSecond,
	InvincibilityTime,
	HitboxRadius,
	MoveSpeedMultiplier,
	RunSpeedMultiplier,
	StaminaMultiplier,
	MaxStaminaMultiplier,
	IncomingDamageMultiplier,
	OutgoingDamageMultiplier,
	CriticalChanceMultiplier,
	CriticalDamageMultiplier,
	AttackSpeedMultiplier,
	ProjectileMultiplier,
	XpMultiplier,
	BloomMultiplier,
	RecoilMultiplier,
}
